# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(400, 601)
        MainWindow.setMaximumSize(QtCore.QSize(400, 16777215))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 10, 380, 30))
        self.label.setMaximumSize(QtCore.QSize(380, 30))
        self.label.setObjectName("label")
        self.input = QtWidgets.QTextEdit(self.centralwidget)
        self.input.setGeometry(QtCore.QRect(10, 40, 280, 40))
        self.input.setObjectName("input")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 90, 380, 30))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(10, 120, 100, 30))
        self.label_3.setObjectName("label_3")
        self.klucz_transpozycja = QtWidgets.QSpinBox(self.centralwidget)
        self.klucz_transpozycja.setGeometry(QtCore.QRect(120, 120, 100, 30))
        self.klucz_transpozycja.setMinimum(1)
        self.klucz_transpozycja.setObjectName("klucz_transpozycja")
        self.szyfruj_transpozycja = QtWidgets.QPushButton(self.centralwidget)
        self.szyfruj_transpozycja.setGeometry(QtCore.QRect(10, 170, 100, 30))
        self.szyfruj_transpozycja.setObjectName("szyfruj_transpozycja")
        self.odszyfruj_transpozycja = QtWidgets.QPushButton(self.centralwidget)
        self.odszyfruj_transpozycja.setGeometry(QtCore.QRect(120, 170, 100, 30))
        self.odszyfruj_transpozycja.setObjectName("odszyfruj_transpozycja")
        self.output = QtWidgets.QTextEdit(self.centralwidget)
        self.output.setGeometry(QtCore.QRect(10, 330, 380, 40))
        self.output.setObjectName("output")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(10, 210, 380, 30))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(10, 240, 100, 30))
        self.label_5.setObjectName("label_5")
        self.klucz__monoalfabet = QtWidgets.QTextEdit(self.centralwidget)
        self.klucz__monoalfabet.setGeometry(QtCore.QRect(120, 240, 100, 30))
        self.klucz__monoalfabet.setObjectName("klucz__monoalfabet")
        self.odszyfruj__monoalfabet = QtWidgets.QPushButton(self.centralwidget)
        self.odszyfruj__monoalfabet.setGeometry(QtCore.QRect(120, 280, 100, 30))
        self.odszyfruj__monoalfabet.setObjectName("odszyfruj__monoalfabet")
        self.szyfruj_monoalfabet = QtWidgets.QPushButton(self.centralwidget)
        self.szyfruj_monoalfabet.setGeometry(QtCore.QRect(10, 280, 100, 30))
        self.szyfruj_monoalfabet.setObjectName("szyfruj_monoalfabet")
        self.file = QtWidgets.QPushButton(self.centralwidget)
        self.file.setGeometry(QtCore.QRect(290, 40, 100, 40))
        self.file.setObjectName("file")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Podaj tekst:"))
        self.label_2.setText(_translate("MainWindow", "METODA TRANSPOZYCJI"))
        self.label_3.setText(_translate("MainWindow", "Podaj klucz:"))
        self.szyfruj_transpozycja.setText(_translate("MainWindow", "Szyfruj"))
        self.odszyfruj_transpozycja.setText(_translate("MainWindow", "Odszyfruj"))
        self.label_4.setText(_translate("MainWindow", "METODA MONOALFABETYCZNA"))
        self.label_5.setText(_translate("MainWindow", "Podaj słowo klucz:"))
        self.odszyfruj__monoalfabet.setText(_translate("MainWindow", "Odszyfruj"))
        self.szyfruj_monoalfabet.setText(_translate("MainWindow", "Szyfruj"))
        self.file.setText(_translate("MainWindow", "Wczytaj z pliku"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
